Repository rocky02/q_it, pull requests merged in 2019-04, with the labels that each got.

#2 Configuration loaded from YAML file
  .gitignore
  .ruby-version
  load_aws.rb
Labels: Review Required

#4 Added support for bundler
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app.rb
  publisher.rb
Labels: Changes Requested

#1 created a basic message publisher for aws sqs with standard queues and added some basic information to Readme.md
  .gitignore
  .ruby-gemset
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  app.rb
  publisher.rb
Labels: Review Required

#3 created subscriber service for aws sqs queues
  README.md
  subscriber.rb
Labels: Changes Requested

#6 Made app.rb file as single point of entry for pub/sub service
  README.md
  app.rb
  publisher.rb
  subscriber.rb
Labels: Review Required, enhancement

#12 Extracted aws sqs credentials and client into a different class and using that for publishing/subscribing
  aws_sqs_client.rb
  publisher.rb
  subscriber.rb
Labels: Refactor, Review Required

#13 Validations for sleep_time for publisher and subscriber and SQS URL validation for subscriber
  README.md
  app.rb
  publisher.rb
  q_it_errors.rb
  subscriber.rb
Labels: Review Required

#14 Feature/app framework and executable file
  .gitignore
  bin/app.rb
  bin/q_it_server
  config/q_it.rb
  lib/aws_sqs_client.rb
  lib/load_aws.rb
  lib/publisher.rb
  lib/q_it_errors.rb
  lib/subscriber.rb
Labels: Review Required
